### PR TITLE
Merging app-trustee into PriFi-SDA

### PR DESCRIPTION
**Pull request by Pamoi**
The app-trustee branch contains the app, service and adapted prifi-sda-wrapper protocol code to run a PriFi node as a single process. It now works and it is possible to use the SOCKS integration. I think it is ready to be merged in the PriFi-SDA branch.

### CODE REVIEW

**Comment by lbarman** [comment]
hi Matthieu, the code looks good, I like it! I have something wrong in my setup, if I try to run
`cd sda/app; go run prifi.go`

I get
`prifi.go:19:2: cannot find package "github.com/lbarman/prifi_dev/sda/services" in any of:
	/usr/lib/golang/src/github.com/lbarman/prifi_dev/sda/services (from $GOROOT)
	/d/Workspace_GO/src/github.com/lbarman/prifi_dev/sda/services (from $GOPATH)`

my current setup:
`/d/go/src/github.com/lbarman/prifi_dev` is on branch `app-trustee`, HEAD
`/d/go/src/github.com/dedis/cothority` is on branch `prifi`, HEAD

did I do something wrong?

**Comment by Pamoi** [comment]
Hello Ludovic,

It works on my machine with this setup. It seems that the compiler may be unhappy because the package in `sda/services` is not named `services` but `prifi`. Maybe this behavior changed in some new version of Go, which version are you running ? I am running 1.7.3.

**Comment by lbarman** [comment]
Hey,
No, that was also my guess, but changing it does not help. I'm running 1.6.3, which seems the latest for Fedora. I'll keep looking into it, please tell me if you have any ideas.

**Comment by lbarman** [comment]
Prior the merge, we need to fix both https://github.com/lbarman/prifi_dev/issues/31 and https://github.com/lbarman/prifi_dev/issues/32

**Pull request closed without merging**
