### PR TITLE
Fix memory leak: clean history when round is done

### PR DESCRIPTION
**Pull request by cmalchik**
The relay's memory usage increases by a few hundred MB per minute due to messages kept after they are no longer needed.  This change deletes the unneeded data at the end of each round.

### CODE REVIEW

**Comment by ineiti** [comment]
I don't know the state of tests in prifi - but would it be possible to create a test to make sure this works as required?

**Comment by cmalchik** [comment]
There are some integration tests which check that the protocol runs, suggesting that we are not deleting too much.  Beyond that, automated testing for memory leaks seems difficult because memory usage may increase for good reason.

I'll merge this in a few days if you don't object.

**Comment by ineiti** [comment]
I think @lbarman should approve - can you put him in the reviewers?

**Comment by cmalchik** [comment]
Ludovic is no longer working on PriFi officially, though he voiced approval for the patch over email.  It looks like there are some broken tests that are blocking merging (not sure if I can bypass them).  I don't have the permissions to access the repo's test settings, but the problems might be related to these issues:

https://github.com/travis-ci/travis-ci/issues/10204
https://github.com/lemurheavy/coveralls-public/issues/905

Could you possibly look into this?

**Comment by ineiti** [comment]
I discussed yesterday with Ludovic and he explained me the situation. I think the best is to add you to dedis/prifi with write access, so that you can correctly launch the tests. Then you'll have to re-create the branch in the dedis/prifi repo, and it should be OK.

@jeffallen @pierluca - can you add @cmalchik with write permission to dedis/prifi? He's the new supporter of it...

**Pull request merged**
