### PR TITLE
Porting PriFi to SDA

### PR DESCRIPTION
**Pull request by lbarman**
The PriFi protocol has been recoded on top of SDA (https://github.com/dedis/cothority/).

This code should be much easier to maintain, and should replace the current master once it is debugged, and especially when we know how to merge the anonymous authentication (DAGA) into it.

For now, this pull request is just to remind everyone that theoretically, this branch should replace the content of master.

### CODE REVIEW

**Comment by ashizam** [comment]
@lbarman @Pamoi @jksarathy 
PriFi-SDA merged with PriFi-SDA-app and the latter was deleted. Please commit SDA-related stuff directly to the PriFi-SDA branch unless there's a major line of work that requires a new branch. Adding new branches that are essentially continuations of an existing branch adds unnecessary confusion.

@Pamoi: We should probably merge PriFi-SDA with example-protocol and app-trustee branches too, right? 

Also, please check the [branches graph](https://github.com/lbarman/prifi_dev/network) frequently to follow the logical lines of work.

**Comment by Pamoi** [comment]
@mahdiz What I intended to do with the example-protocol branch was to provide a code skeleton to start implementing SDA protocols with extensive comments. If we merge it it will disappear as this code is useless for PriFi, I put it in a separate branch to serve as an example for future contributors trying to understand how SDA works.
The app-trustee is my working branch and is destined to be merged with PriFI-SDA when it's code is working. I prefer developing in a separate branch so it is easier for me to throw things away if they don't work. I can keep it local but having it in GitHub allows me to easily show my progress to @lbarman and @italod

**Comment by ashizam** [comment]
Thanks for the clarification, @pamoi! Let's keep the app-trustee branch then. For future, I suggest using our GitHub IDs as our personal branch names (e.g., as done by Mohamad before) to make it clear that the branch won't be part of the main merge flow.

As far as I understood, the example-protocol adds useful comments and some minor changes to Ludovic's skeleton branch (PriFi-SDA-app) and hence is good to be merged with PriFi-SDA, right?

I suggest we work on PriFi-SDA as our main progress branch in porting PriFi into SDA. We can of course have our own personal branches, too :)

**Comment by Pamoi** [comment]
@mahdiz Ok for the branch naming. However the PriFi-SDA branch will contain the real PriFi app/service/protocol and the example template will disappear if we merge it in this branch. I created the example-protocol to keep it as it is extremely easier to understand than the real PriFi protocol and will serve as an example to familiarize new contributors with SDA.

**Comment by ashizam** [comment]
Got you, @Pamoi, let's keep the example branch, too :)

**Pull request merged**
